import { config as loadEnv } from "dotenv";
import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

import { createClient } from "@supabase/supabase-js";

type StaffCredRow = {
  email: string;
  password: string;
  role: string;
  restaurantsAccessCount: number;
  userId: string;
};

function requireEnv(key: string): string {
  const value = (process.env[key] ?? "").trim();
  if (!value) throw new Error(`Missing env var: ${key}`);
  return value;
}

function findLatestCredsCsv(backupsDir: string): string {
  const candidates = fs
    .readdirSync(backupsDir, { withFileTypes: true })
    .filter((d) => d.isFile() && d.name.startsWith("staging-staff-creds-") && d.name.endsWith(".csv"))
    .map((d) => path.join(backupsDir, d.name))
    .sort((a, b) => b.localeCompare(a));

  if (candidates.length === 0) {
    throw new Error(`No staging staff creds CSV found in ${backupsDir}. Run scripts/staging/import-prod-staff.ts first.`);
  }

  return candidates[0];
}

function parseCredsCsv(raw: string): StaffCredRow[] {
  const lines = raw
    .split("\n")
    .map((l) => l.trim())
    .filter(Boolean);

  if (lines.length < 2) return [];

  const header = lines[0] ?? "";
  const headerCols = header.split(",").map((c) => c.trim());

  const expectedHeaderA = ["email", "password", "role", "restaurants_access_count", "user_id"];
  const expectedHeaderB = ["email", "password", "role", "restaurants_count", "user_id"]; // legacy header
  const isExpectedA = expectedHeaderA.every((col, idx) => headerCols[idx] === col);
  const isExpectedB = expectedHeaderB.every((col, idx) => headerCols[idx] === col);
  if (!isExpectedA && !isExpectedB) {
    throw new Error(
      `Unexpected CSV header. Expected: ${expectedHeaderA.join(",")} | Got: ${headerCols.slice(0, 8).join(",")}`,
    );
  }

  const rows: StaffCredRow[] = [];
  for (const line of lines.slice(1)) {
    // This CSV is generated by our script and does not use quoted values.
    const cols = line.split(",");
    if (cols.length < 5) continue;
    const [email, password, role, accessCountRaw, userId] = cols;
    const restaurantsAccessCount = Number.parseInt((accessCountRaw ?? "").trim(), 10);
    rows.push({
      email: (email ?? "").trim(),
      password: (password ?? "").trim(),
      role: (role ?? "").trim(),
      restaurantsAccessCount: Number.isFinite(restaurantsAccessCount) ? restaurantsAccessCount : 0,
      userId: (userId ?? "").trim(),
    });
  }

  return rows.filter((r) => r.email && r.password && r.userId);
}

async function main() {
  const modulePath = fileURLToPath(import.meta.url);
  const repoRoot = path.resolve(path.dirname(modulePath), "../..");
  const envLocalPath = path.join(repoRoot, ".env.local");
  if (fs.existsSync(envLocalPath)) {
    loadEnv({ path: envLocalPath, override: false });
  }

  const supabaseUrl = requireEnv("NEXT_PUBLIC_SUPABASE_URL");
  const anonKey = requireEnv("NEXT_PUBLIC_SUPABASE_ANON_KEY");

  const backupsDir = path.join(repoRoot, "backups");
  const csvPath = process.env.STAGING_STAFF_CREDS_CSV?.trim() || findLatestCredsCsv(backupsDir);

  const limitRaw = (process.env.SMOKE_LIMIT ?? "").trim();
  const limit = limitRaw ? Math.max(1, Number.parseInt(limitRaw, 10)) : 3;

  const rows = parseCredsCsv(fs.readFileSync(csvPath, "utf-8"));
  if (rows.length === 0) {
    throw new Error(`No rows parsed from ${csvPath}.`);
  }

  // One row per user, but be defensive.
  const uniqueByEmail = new Map<string, StaffCredRow>();
  for (const row of rows) uniqueByEmail.set(row.email, row);

  const sample = Array.from(uniqueByEmail.values()).slice(0, limit);
  console.log(`[smoke-auth] Using creds CSV: ${csvPath}`);
  console.log(`[smoke-auth] Testing ${sample.length} user(s) against ${supabaseUrl}`);

  for (const row of sample) {
    const userClient = createClient(supabaseUrl, anonKey, {
      auth: {
        autoRefreshToken: false,
        persistSession: false,
      },
    });

    const signIn = await userClient.auth.signInWithPassword({ email: row.email, password: row.password });
    if (signIn.error || !signIn.data.session) {
      throw new Error(`[smoke-auth] Sign-in failed for ${row.email}: ${signIn.error?.message ?? "no session"}`);
    }

    const authedUserId = signIn.data.user?.id ?? "";
    if (!authedUserId) throw new Error(`[smoke-auth] Missing user id after sign-in for ${row.email}`);

    // RLS check: can read their memberships (should be true for ops users).
    const memberships = await userClient.from("restaurant_memberships").select("restaurant_id, role");
    if (memberships.error) {
      throw new Error(`[smoke-auth] Membership query failed for ${row.email}: ${memberships.error.message}`);
    }

    // RLS check: can list their restaurants via an inner join.
    const restaurants = await userClient
      .from("restaurants")
      .select("id, name, restaurant_memberships!inner(role)")
      .eq("restaurant_memberships.user_id", authedUserId);

    if (restaurants.error) {
      throw new Error(`[smoke-auth] Restaurant list query failed for ${row.email}: ${restaurants.error.message}`);
    }

    console.log(
      `[smoke-auth] OK: ${row.email} role=${row.role} memberships=${memberships.data?.length ?? 0} restaurants=${restaurants.data?.length ?? 0}`,
    );

    // Basic consistency check with the count we exported.
    const actualCount = restaurants.data?.length ?? 0;
    if (row.restaurantsAccessCount && row.restaurantsAccessCount !== actualCount) {
      console.warn(
        `[smoke-auth] WARN: ${row.email} expected restaurants_access_count=${row.restaurantsAccessCount} but RLS-visible restaurants=${actualCount}`,
      );
    }
  }

  console.log("[smoke-auth] Done.");
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
