export const TEMPLATE_DEFINITIONS = [
  {
    key: 'request_received',
    title: 'Request Received',
    description: 'Pending booking requests awaiting review.',
    group: 'request',
    supportsCtaLabel: true,
    recommendedVariables: ['venue', 'date', 'time', 'party'],
    authoringHints: [
      'Set expectations clearly and reassure the guest that the venue is reviewing availability.',
      'Keep the CTA status-oriented rather than sales-oriented.',
    ],
    defaultVariants: [
      {
        id: 'request-received-default-1',
        name: 'Request Received',
        subject: 'Reservation request received at {{venue}}',
        preheader: 'We are checking availability for {{date}} at {{time}}.',
        headline: 'Request received',
        intro:
          'We have received your request for {{party}} at {{venue}} on {{date}} at {{time}} and are checking availability now.',
        cue: '',
        ask: '',
        ctaLabel: 'Check Status',
      },
      {
        id: 'request-received-default-2',
        name: 'Checking Availability',
        subject: 'We are reviewing your request for {{venue}}',
        preheader: 'Your requested table is being checked now.',
        headline: 'We are checking availability',
        intro:
          'Your request for {{date}} at {{time}} at {{venue}} is with the team now. We will confirm as soon as a table is available.',
        cue: '',
        ask: '',
        ctaLabel: 'Check Status',
      },
      {
        id: 'request-received-default-3',
        name: 'Awaiting Confirmation',
        subject: 'We will confirm your request for {{venue}} shortly',
        preheader: 'Thanks for your request. We will be back in touch soon.',
        headline: 'Awaiting confirmation',
        intro:
          'Thanks for your request at {{venue}} for {{party}} on {{date}} at {{time}}. We are reviewing it and will follow up shortly.',
        cue: '',
        ask: '',
        ctaLabel: 'View Request',
      },
    ],
  },
  {
    key: 'confirmation',
    title: 'Confirmation',
    description: 'Confirmed reservations for accepted bookings.',
    group: 'confirmation',
    supportsCtaLabel: true,
    recommendedVariables: ['firstName', 'venue', 'date', 'time', 'party'],
    authoringHints: [
      'Lead with reassurance that the table is secured.',
      'Use the intro to reinforce the concrete reservation details and next step.',
    ],
    defaultVariants: [
      {
        id: 'confirmation-default-1',
        name: 'Reservation Confirmed',
        subject: 'Your table at {{venue}} is confirmed',
        preheader: '{{date}} at {{time}} for {{party}} is secured.',
        headline: 'Your reservation is confirmed',
        intro: '{{firstName}}, your table for {{party}} at {{venue}} is confirmed for {{date}} at {{time}}.',
        cue: 'If the meal turns into a favorite, feel free to snap a photo and add it to a quick review afterward.',
        ask: '',
        ctaLabel: 'Manage Booking',
      },
      {
        id: 'confirmation-default-2',
        name: 'All Set',
        subject: 'Confirmed: {{venue}} on {{date}}',
        preheader: 'Everything is set for {{time}}.',
        headline: 'You are all set',
        intro: 'We have locked in your reservation at {{venue}} for {{date}} at {{time}} for {{party}}.',
        cue: 'A quick photo and short review after your visit can help future guests choose with confidence.',
        ask: '',
        ctaLabel: 'Manage Booking',
      },
      {
        id: 'confirmation-default-3',
        name: 'Table Secured',
        subject: 'See you soon at {{venue}}',
        preheader: 'Your reservation details are ready to go.',
        headline: 'Table secured',
        intro: 'Your booking at {{venue}} is secured. You are booked for {{date}} at {{time}} for {{party}}.',
        cue: 'If you end up taking a favorite photo, you can always add it to a review after your visit.',
        ask: '',
        ctaLabel: 'Manage Booking',
      },
    ],
  },
  {
    key: 'modification_pending',
    title: 'Change Requested',
    description: 'Guest-requested reservation changes awaiting review.',
    group: 'changes',
    supportsCtaLabel: true,
    recommendedVariables: ['venue', 'date', 'time', 'party'],
    authoringHints: [
      'Acknowledge the requested change and set the expectation that confirmation follows separately.',
    ],
    defaultVariants: [
      {
        id: 'modification-pending-default-1',
        name: 'Change Request Received',
        subject: 'Change request received for {{venue}}',
        preheader: 'We are reviewing your updated booking details.',
        headline: 'Your change request is in',
        intro:
          'We have received your requested update for {{venue}} on {{date}} at {{time}} for {{party}}. We are reviewing availability now.',
        cue: '',
        ask: '',
        ctaLabel: 'View Request',
      },
      {
        id: 'modification-pending-default-2',
        name: 'Reviewing Your Update',
        subject: 'We are reviewing your reservation change',
        preheader: 'We will confirm the updated details shortly.',
        headline: 'We are reviewing your update',
        intro:
          'Your request to update your reservation at {{venue}} for {{date}} at {{time}} is being checked by the team now.',
        cue: '',
        ask: '',
        ctaLabel: 'View Request',
      },
      {
        id: 'modification-pending-default-3',
        name: 'Awaiting Updated Confirmation',
        subject: 'We have your updated request for {{venue}}',
        preheader: 'We will follow up as soon as the change is confirmed.',
        headline: 'Updated request received',
        intro:
          'Thanks for sending your updated request for {{venue}}. We are checking the new details for {{date}} at {{time}} and will confirm shortly.',
        cue: '',
        ask: '',
        ctaLabel: 'Check Status',
      },
    ],
  },
  {
    key: 'modification_confirmed',
    title: 'Changes Confirmed',
    description: 'Confirmed changes for an existing reservation.',
    group: 'changes',
    supportsCtaLabel: true,
    recommendedVariables: ['firstName', 'venue', 'date', 'time', 'party'],
    authoringHints: ['Call out that the updated reservation is now final and ready.'],
    defaultVariants: [
      {
        id: 'modification-confirmed-default-1',
        name: 'Updated Reservation Confirmed',
        subject: 'Your updated reservation at {{venue}} is confirmed',
        preheader: 'Your new booking details are set.',
        headline: 'Your updated booking is confirmed',
        intro:
          'Your reservation at {{venue}} has been updated and confirmed for {{date}} at {{time}} for {{party}}.',
        cue: '',
        ask: '',
        ctaLabel: 'View Booking',
      },
      {
        id: 'modification-confirmed-default-2',
        name: 'Changes Locked In',
        subject: 'Changes confirmed for {{venue}}',
        preheader: 'Everything is updated and ready to go.',
        headline: 'Your changes are locked in',
        intro: '{{firstName}}, your updated reservation at {{venue}} is all set for {{date}} at {{time}}.',
        cue: '',
        ask: '',
        ctaLabel: 'View Booking',
      },
      {
        id: 'modification-confirmed-default-3',
        name: 'Updated Details Ready',
        subject: 'Your new reservation details are set',
        preheader: 'Your updated booking is ready to view.',
        headline: 'Your new details are ready',
        intro:
          'We have confirmed your updated booking at {{venue}}. Your new reservation is for {{date}} at {{time}} for {{party}}.',
        cue: '',
        ask: '',
        ctaLabel: 'View Booking',
      },
    ],
  },
  {
    key: 'cancelled',
    title: 'Cancelled',
    description: 'Guest-confirmed cancellations.',
    group: 'cancellation',
    supportsCtaLabel: true,
    recommendedVariables: ['venue', 'date', 'time'],
    authoringHints: [
      'Keep the tone calm and empathetic.',
      'If you include a CTA, make it about rebooking rather than account management.',
    ],
    defaultVariants: [
      {
        id: 'cancelled-default-1',
        name: 'Cancellation Confirmed',
        subject: 'Your reservation at {{venue}} has been cancelled',
        preheader: 'You can rebook anytime if plans change.',
        headline: 'Your booking has been cancelled',
        intro: 'As requested, we have cancelled your reservation at {{venue}} for {{date}} at {{time}}.',
        cue: '',
        ask: '',
        ctaLabel: 'Book Again',
      },
      {
        id: 'cancelled-default-2',
        name: 'Reservation Cancelled',
        subject: 'Cancellation confirmed for {{venue}}',
        preheader: 'Your table is no longer reserved.',
        headline: 'Cancellation confirmed',
        intro: 'Your reservation at {{venue}} on {{date}} at {{time}} has been cancelled. We would love to welcome you another time.',
        cue: '',
        ask: '',
        ctaLabel: 'Book Again',
      },
      {
        id: 'cancelled-default-3',
        name: 'Book Another Time',
        subject: 'Your booking at {{venue}} has been released',
        preheader: 'Need another date? Rebook in a few clicks.',
        headline: 'Your table has been released',
        intro: 'We have released your reservation at {{venue}} for {{date}} at {{time}}. If your plans change, you can book again anytime.',
        cue: '',
        ask: '',
        ctaLabel: 'Book Again',
      },
    ],
  },
  {
    key: 'booking_rejected',
    title: 'Unavailable',
    description: 'Requests the venue could not accept.',
    group: 'cancellation',
    supportsCtaLabel: true,
    recommendedVariables: ['venue', 'date', 'time'],
    authoringHints: [
      'Be direct about unavailability and offer a simple alternative next step.',
    ],
    defaultVariants: [
      {
        id: 'booking-rejected-default-1',
        name: 'Requested Time Unavailable',
        subject: '{{venue}} is unavailable at your requested time',
        preheader: 'Try another time or date to book.',
        headline: 'That time is not available',
        intro:
          '{{venue}} is fully booked for {{date}} at {{time}}. If you are flexible, we would love to help you find another time.',
        cue: '',
        ask: '',
        ctaLabel: 'Try Another Time',
      },
      {
        id: 'booking-rejected-default-2',
        name: 'No Table Available',
        subject: 'No table is available at {{venue}} for that time',
        preheader: 'A different slot may still be available.',
        headline: 'No table available for that slot',
        intro: 'We could not confirm a table at {{venue}} for {{date}} at {{time}}. A nearby time may still be open.',
        cue: '',
        ask: '',
        ctaLabel: 'See Other Times',
      },
      {
        id: 'booking-rejected-default-3',
        name: 'Find Another Time',
        subject: 'Let us find another time at {{venue}}',
        preheader: 'Your first choice is full, but other times may work.',
        headline: 'Let us find another time',
        intro:
          'Your requested time at {{venue}} is no longer available. Choose another time and we will help get you booked.',
        cue: '',
        ask: '',
        ctaLabel: 'Choose Another Time',
      },
    ],
  },
  {
    key: 'restaurant_cancellation',
    title: 'Venue Cancellation',
    description: 'Venue-initiated cancellations that prompt a rebook.',
    group: 'cancellation',
    supportsCtaLabel: true,
    recommendedVariables: ['venue', 'date', 'time'],
    authoringHints: [
      'Own the disruption and prioritize apology plus recovery language.',
    ],
    defaultVariants: [
      {
        id: 'restaurant-cancellation-default-1',
        name: 'Important Reservation Update',
        subject: 'Important update about your reservation at {{venue}}',
        preheader: 'We are sorry, your booking cannot go ahead as planned.',
        headline: 'We need to reschedule your booking',
        intro:
          'We are sorry, but {{venue}} needs to cancel your reservation for {{date}} at {{time}} due to an unexpected issue.',
        cue: '',
        ask: '',
        ctaLabel: 'Rebook Now',
      },
      {
        id: 'restaurant-cancellation-default-2',
        name: 'Apology and Rebook',
        subject: 'We are sorry — your reservation has been cancelled',
        preheader: 'Please choose a new time that works for you.',
        headline: 'We are sorry for the change',
        intro:
          'Unfortunately, {{venue}} can no longer honor your reservation for {{date}} at {{time}}. We are sorry for the disruption.',
        cue: '',
        ask: '',
        ctaLabel: 'Choose a New Time',
      },
      {
        id: 'restaurant-cancellation-default-3',
        name: 'Please Rebook',
        subject: 'Please rebook your visit to {{venue}}',
        preheader: 'We would love to help you secure another table.',
        headline: 'Please choose a new time',
        intro:
          'An unexpected issue means we have had to cancel your reservation at {{venue}} for {{date}} at {{time}}. Please choose a new time and we will take it from there.',
        cue: '',
        ask: '',
        ctaLabel: 'Rebook Your Visit',
      },
    ],
  },
  {
    key: 'review_request',
    title: 'Review Request',
    description: 'Post-visit review prompts.',
    group: 'review',
    supportsCtaLabel: true,
    recommendedVariables: ['firstName', 'venue'],
    authoringHints: [
      'Ask for feedback simply and keep the effort low.',
      'Variants should differ in tone, not in the destination or ask.',
    ],
    defaultVariants: [
      {
        id: 'review-request-default-1',
        name: 'Quick Review',
        subject: 'How was your visit to {{venue}}?',
        preheader: 'A quick review helps and only takes a moment.',
        headline: 'How was everything?',
        intro: 'Thanks for visiting {{venue}}. Could you spare 30 seconds to leave a quick review?',
        cue: '',
        ask: 'If you took a photo during your visit, adding one to your review makes it even more helpful.',
        ctaLabel: 'Leave a Review',
      },
      {
        id: 'review-request-default-2',
        name: 'Would You Review Us?',
        subject: 'Would you review {{venue}}?',
        preheader: 'Your feedback helps future guests decide.',
        headline: 'We would love your feedback',
        intro: '{{firstName}}, thanks for dining with us at {{venue}}. We would really appreciate a quick review.',
        cue: '',
        ask: 'If you snapped a favorite photo, feel free to include it with your review.',
        ctaLabel: 'Leave a Review',
      },
      {
        id: 'review-request-default-3',
        name: 'Tell Us How We Did',
        subject: 'Tell us about your experience at {{venue}}',
        preheader: 'Share a short review after your visit.',
        headline: 'Tell us how we did',
        intro: 'We hope you had a great experience at {{venue}}. A short review goes a long way.',
        cue: '',
        ask: 'A photo from your visit can help other guests know what to expect.',
        ctaLabel: 'Leave a Review',
      },
    ],
  },
  {
    key: 'reminder_24h',
    title: '24 Hour Reminder',
    description: 'Day-before reminder emails.',
    group: 'reminder',
    supportsCtaLabel: true,
    recommendedVariables: ['firstName', 'venue', 'date', 'time', 'party'],
    authoringHints: ['Focus on readiness and arrival confidence.'],
    defaultVariants: [
      {
        id: 'reminder-24h-default-1',
        name: 'Reservation Tomorrow',
        subject: 'Reminder: your reservation at {{venue}} is tomorrow',
        preheader: '{{date}} at {{time}} for {{party}}.',
        headline: 'Your reservation is tomorrow',
        intro: 'Just a reminder that you are booked at {{venue}} tomorrow at {{time}} for {{party}}.',
        cue: 'If you end up having a great time, a quick photo and short review afterward is always appreciated.',
        ask: '',
        ctaLabel: 'Get Directions',
      },
      {
        id: 'reminder-24h-default-2',
        name: 'See You Tomorrow',
        subject: 'See you tomorrow at {{venue}}',
        preheader: 'Your table is nearly ready.',
        headline: 'See you tomorrow',
        intro: 'You are all set for {{venue}} tomorrow at {{time}}. We are looking forward to welcoming your party of {{party}}.',
        cue: 'If the visit is worth sharing, a quick photo and short review afterward helps other guests too.',
        ask: '',
        ctaLabel: 'Get Directions',
      },
      {
        id: 'reminder-24h-default-3',
        name: 'Ready for Your Visit',
        subject: 'Your table at {{venue}} is almost ready',
        preheader: 'Everything is in place for tomorrow.',
        headline: 'We are ready for your visit',
        intro: 'This is your day-before reminder for {{venue}} on {{date}} at {{time}} for {{party}}.',
        cue: 'If you take a favorite photo tomorrow, you can always add it to a quick review afterward.',
        ask: '',
        ctaLabel: 'Plan Your Route',
      },
    ],
  },
  {
    key: 'reminder_short',
    title: 'Arrival Reminder',
    description: 'Same-day or arrival-time reminders.',
    group: 'reminder',
    supportsCtaLabel: true,
    recommendedVariables: ['venue', 'time'],
    authoringHints: [
      'Keep the copy short and action-oriented because the guest is close to arrival.',
    ],
    defaultVariants: [
      {
        id: 'reminder-short-default-1',
        name: 'Table Ready',
        subject: 'Your table at {{venue}} is ready',
        preheader: 'Head to the host stand when you arrive.',
        headline: 'Your table is ready',
        intro: 'We have prepared your table at {{venue}}. Please head to the host stand when you arrive.',
        cue: '',
        ask: '',
        ctaLabel: "I'm Here",
      },
      {
        id: 'reminder-short-default-2',
        name: 'See You Shortly',
        subject: 'See you shortly at {{venue}}',
        preheader: 'Please check in with the host stand when you arrive.',
        headline: 'See you shortly',
        intro: 'You are due at {{venue}} around {{time}}. When you arrive, please check in with the host stand.',
        cue: '',
        ask: '',
        ctaLabel: "I'm Here",
      },
      {
        id: 'reminder-short-default-3',
        name: 'Ready When You Are',
        subject: 'We are ready for you at {{venue}}',
        preheader: 'Let the host know once you have arrived.',
        headline: 'We are ready when you are',
        intro: 'Your visit to {{venue}} is coming up. Let the host stand know when you arrive and we will take it from there.',
        cue: '',
        ask: '',
        ctaLabel: "I'm Here",
      },
    ],
  },
] as const satisfies ReadonlyArray<{
  key: string;
  title: string;
  description: string;
  group: string;
  supportsCtaLabel: boolean;
  recommendedVariables: readonly string[];
  authoringHints: readonly string[];
  defaultVariants: ReadonlyArray<{
    id: string;
    name: string;
    subject: string;
    preheader: string;
    headline: string;
    intro: string;
    cue: string;
    ask: string;
    ctaLabel: string;
  }>;
}>;
