import { createHash } from 'node:crypto';
import { createReadStream, mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import type { LimaConfig } from '../config';
import { assertContext, assertName, type DockerContextSpec } from '../docker/command';
import { assertSucceeded, type CommandRunner } from '../runner';
import type { PlannedCommand } from '../spool/bundle';

/**
 * Disposable Lima instance lifecycle.
 *
 * - Cold clone from a digest-verified, pre-provisioned base image for every
 *   job; snapshots are never created or restored.
 * - An explicit docker context (`nabatable-ci`) points at the instance's docker
 *   socket; `docker context use` is never called and protected contexts
 *   (`default`, `desktop-linux`) are never touched.
 * - The bundle enters the guest through `limactl copy`; no host mounts, no port
 *   forwards, no proxy env propagation.
 * - The instance is destroyed after collection even when anything fails.
 */

export interface LimaInstanceInput {
  readonly jobId: string;
  readonly config: LimaConfig;
  readonly jobDir: string;
  readonly limaHome: string;
}

export interface LimaDeps {
  readonly runner: CommandRunner;
  readonly pathEnv: string;
  readonly digestFile?: (filePath: string) => Promise<string>;
  /**
   * Job-private DOCKER_CONFIG directory. The CI docker context is created and
   * removed there, so the operator's ~/.docker (and its contexts) is never read
   * or written.
   */
  readonly dockerConfigDir?: string;
}

export interface LimaHandle {
  readonly name: string;
  readonly docker: DockerContextSpec;
  readonly dockerSocket: string;
  copyIn(localPath: string, guestPath: string): Promise<void>;
  shell(args: readonly string[], purpose: string, timeoutMs?: number): Promise<string>;
}

export class LimaImageDigestError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'LimaImageDigestError';
  }
}

export interface LimaDestroyReport {
  readonly attempted: readonly string[];
  readonly failures: readonly string[];
}

export function dockerContextSpec(config: LimaConfig): DockerContextSpec {
  return { context: config.dockerContext, protectedContexts: config.protectedDockerContexts };
}

export function limaInstanceName(config: LimaConfig, jobId: string): string {
  const name = `${config.instancePrefix}-${jobId}`.toLowerCase().replace(/[^a-z0-9-]/gu, '-');
  assertName(name, 'lima instance name');
  return name;
}

export function limaDockerSocket(limaHome: string, instanceName: string): string {
  return path.join(limaHome, instanceName, 'sock', 'docker.sock');
}

/**
 * Per-job Lima template. Mirrors the hardening of
 * infra/local-ci/lima/nabatable-ci.yaml (no mounts, no TCP port forwards, no
 * proxy/env propagation, no agent forwarding, no containerd) while pointing at
 * the local pre-provisioned image. The only forward is the docker unix socket.
 */
export function renderLimaTemplate(config: LimaConfig): string {
  return [
    '# Generated by scripts/ci/executor for a single disposable CI job. Do not edit.',
    'vmType: vz',
    'os: Linux',
    'arch: aarch64',
    'images:',
    `  - location: "file://${config.baseImagePath}"`,
    '    arch: aarch64',
    `    digest: "${config.baseImageDigest}"`,
    `cpus: ${config.cpus}`,
    `memory: "${config.memoryGiB}GiB"`,
    `disk: "${config.diskGiB}GiB"`,
    'mounts: []',
    'ssh:',
    '  localPort: 0',
    '  loadDotSSHPubKeys: false',
    '  forwardAgent: false',
    '  forwardX11: false',
    '  forwardX11Trusted: false',
    'portForwards:',
    '  - guestIP: "0.0.0.0"',
    '    guestPortRange: [1, 65535]',
    '    ignore: true',
    '  - guestSocket: "/var/run/docker.sock"',
    '    hostSocket: "{{.Dir}}/sock/docker.sock"',
    'propagateProxyEnv: false',
    'env: {}',
    'containerd:',
    '  system: false',
    '  user: false',
    'hostResolver:',
    '  enabled: true',
    '  ipv6: false',
    'rosetta:',
    '  enabled: false',
    '  binfmt: false',
    'video:',
    '  display: "none"',
    'audio:',
    '  device: "none"',
    '',
  ].join('\n');
}

export async function sha256File(filePath: string): Promise<string> {
  return new Promise((resolve, reject) => {
    const hash = createHash('sha256');
    createReadStream(filePath)
      .on('data', (chunk) => hash.update(chunk))
      .on('error', reject)
      .on('end', () => resolve(`sha256:${hash.digest('hex')}`));
  });
}

/** The image file on disk must hash to the configured digest before any clone. */
export async function verifyBaseImageDigest(
  config: LimaConfig,
  digestFile: (filePath: string) => Promise<string>,
): Promise<string> {
  let actual: string;
  try {
    actual = await digestFile(config.baseImagePath);
  } catch (error) {
    throw new LimaImageDigestError(
      `base image ${config.baseImagePath} could not be read: ${(error as Error).message}`,
    );
  }
  if (actual !== config.baseImageDigest) {
    throw new LimaImageDigestError(
      `base image on disk (${actual}) does not match configured digest ${config.baseImageDigest}`,
    );
  }
  return actual;
}

function limaEnv(deps: LimaDeps, limaHome: string): Readonly<Record<string, string>> {
  return {
    PATH: deps.pathEnv,
    HOME: path.dirname(limaHome),
    LIMA_HOME: limaHome,
    LC_ALL: 'C',
    ...(deps.dockerConfigDir ? { DOCKER_CONFIG: deps.dockerConfigDir } : {}),
  };
}

export function planLima(input: LimaInstanceInput, bundlePath: string): readonly PlannedCommand[] {
  const name = limaInstanceName(input.config, input.jobId);
  const templatePath = path.join(input.jobDir, 'lima.yaml');
  const socket = limaDockerSocket(input.limaHome, name);
  const context = input.config.dockerContext;
  return [
    { purpose: 'verify base image digest', command: 'sha256', args: [input.config.baseImagePath] },
    {
      purpose: 'create disposable instance (cold clone)',
      command: 'limactl',
      args: ['create', '--tty=false', `--name=${name}`, templatePath],
    },
    { purpose: 'start instance', command: 'limactl', args: ['start', '--tty=false', name] },
    {
      purpose: 'bind docker context to the instance socket',
      command: 'docker',
      args: ['context', 'create', context, '--docker', `host=unix://${socket}`],
    },
    {
      purpose: 'copy bundle into guest',
      command: 'limactl',
      args: ['copy', bundlePath, `${name}:${input.config.guestSpoolDir}/job.bundle`],
    },
    { purpose: 'destroy: stop instance', command: 'limactl', args: ['stop', '--force', name] },
    { purpose: 'destroy: delete instance', command: 'limactl', args: ['delete', '--force', name] },
    {
      purpose: 'destroy: remove docker context',
      command: 'docker',
      args: ['context', 'rm', '--force', context],
    },
  ];
}

export async function destroyLimaInstance(
  input: LimaInstanceInput,
  deps: LimaDeps,
  name: string,
): Promise<LimaDestroyReport> {
  const env = limaEnv(deps, input.limaHome);
  const context = input.config.dockerContext;
  const attempted: string[] = [];
  const failures: string[] = [];
  const steps: Array<{ purpose: string; command: string; args: readonly string[] }> = [
    { purpose: 'stop instance', command: 'limactl', args: ['stop', '--force', name] },
    { purpose: 'delete instance', command: 'limactl', args: ['delete', '--force', name] },
    {
      purpose: 'remove docker context',
      command: 'docker',
      args: ['context', 'rm', '--force', context],
    },
  ];
  for (const step of steps) {
    attempted.push(step.purpose);
    try {
      const result = await deps.runner.run({ ...step, env, timeoutMs: 5 * 60_000 });
      if (result.exitCode !== 0) failures.push(`${step.purpose}: exit ${result.exitCode}`);
    } catch (error) {
      failures.push(`${step.purpose}: ${(error as Error).message}`);
    }
  }
  return { attempted, failures };
}

export class LimaJobError extends Error {
  constructor(
    message: string,
    readonly destroy: LimaDestroyReport,
    readonly cause: unknown,
  ) {
    super(message);
    this.name = 'LimaJobError';
  }
}

/**
 * Create a fresh instance, run `body`, and destroy the instance in every path.
 * The destroy report is attached to the result (or the error) so callers can
 * surface leaks.
 */
export async function withLimaInstance<T>(
  input: LimaInstanceInput,
  deps: LimaDeps,
  body: (handle: LimaHandle) => Promise<T>,
): Promise<{ value: T; destroy: LimaDestroyReport }> {
  const docker = dockerContextSpec(input.config);
  assertContext(docker);
  const digestFile = deps.digestFile ?? sha256File;
  await verifyBaseImageDigest(input.config, digestFile);

  const name = limaInstanceName(input.config, input.jobId);
  const env = limaEnv(deps, input.limaHome);
  const socket = limaDockerSocket(input.limaHome, name);
  const context = input.config.dockerContext;
  mkdirSync(input.jobDir, { recursive: true, mode: 0o700 });
  const templatePath = path.join(input.jobDir, 'lima.yaml');
  writeFileSync(templatePath, renderLimaTemplate(input.config), { mode: 0o600 });

  const run = async (
    command: string,
    args: readonly string[],
    purpose: string,
    timeoutMs = 10 * 60_000,
  ) => {
    const result = await deps.runner.run({ command, args, env, purpose, timeoutMs });
    assertSucceeded(result, purpose);
    return result;
  };

  try {
    await run(
      'limactl',
      ['create', '--tty=false', `--name=${name}`, templatePath],
      'create instance',
    );
    await run('limactl', ['start', '--tty=false', name], 'start instance', 15 * 60_000);
    // Never `docker context use`; protected contexts stay untouched.
    await deps.runner.run({
      command: 'docker',
      args: ['context', 'rm', '--force', context],
      env,
      purpose: 'remove stale docker context',
      timeoutMs: 60_000,
    });
    await run(
      'docker',
      ['context', 'create', context, '--docker', `host=unix://${socket}`],
      'create docker context',
      60_000,
    );

    const handle: LimaHandle = {
      name,
      docker,
      dockerSocket: socket,
      async copyIn(localPath, guestPath) {
        await run(
          'limactl',
          ['copy', localPath, `${name}:${guestPath}`],
          'copy into guest',
          15 * 60_000,
        );
      },
      async shell(args, purpose, timeoutMs) {
        const result = await run(
          'limactl',
          ['shell', '--tty=false', name, '--', ...args],
          purpose,
          timeoutMs,
        );
        return result.stdout;
      },
    };
    const value = await body(handle);
    return { value, destroy: await destroyLimaInstance(input, deps, name) };
  } catch (error) {
    // Always attempt teardown: a half-created instance must not survive a failure.
    const destroy = await destroyLimaInstance(input, deps, name);
    throw new LimaJobError((error as Error).message, destroy, error);
  }
}
