-- Manual assignment sessions and hold lifecycle
-- Generated by Codex on 2025-11-17

BEGIN;

-- State enums
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_type WHERE typname = 'manual_assignment_session_state'
  ) THEN
    CREATE TYPE public.manual_assignment_session_state AS ENUM (
      'none',
      'proposed',
      'held',
      'confirmed',
      'expired',
      'conflicted',
      'cancelled'
    );
  END IF;
END$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_type WHERE typname = 'table_hold_status'
  ) THEN
    CREATE TYPE public.table_hold_status AS ENUM (
      'active',
      'expired',
      'confirmed',
      'cancelled'
    );
  END IF;
END$$;

-- Session table
CREATE TABLE IF NOT EXISTS public.manual_assignment_sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL REFERENCES public.bookings(id) ON DELETE CASCADE,
  restaurant_id uuid NOT NULL REFERENCES public.restaurants(id) ON DELETE CASCADE,
  state public.manual_assignment_session_state NOT NULL DEFAULT 'none',
  selection jsonb,
  selection_version integer NOT NULL DEFAULT 0,
  context_version text,
  policy_version text,
  snapshot_hash text,
  hold_id uuid,
  expires_at timestamptz,
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now()),
  UNIQUE (booking_id)
);

ALTER TABLE public.manual_assignment_sessions
  ADD CONSTRAINT manual_assignment_sessions_hold_fkey
  FOREIGN KEY (hold_id)
  REFERENCES public.table_holds(id)
  ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS mas_booking_state_idx
  ON public.manual_assignment_sessions (booking_id, state);

CREATE INDEX IF NOT EXISTS mas_restaurant_state_idx
  ON public.manual_assignment_sessions (restaurant_id, state);

-- Hold lifecycle fields
ALTER TABLE public.table_holds
  ADD COLUMN IF NOT EXISTS session_id uuid REFERENCES public.manual_assignment_sessions(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS status public.table_hold_status NOT NULL DEFAULT 'active',
  ADD COLUMN IF NOT EXISTS last_touched_at timestamptz NOT NULL DEFAULT timezone('utc'::text, now());

CREATE INDEX IF NOT EXISTS table_holds_session_idx
  ON public.table_holds (session_id);

CREATE INDEX IF NOT EXISTS table_holds_status_idx
  ON public.table_holds (status);

COMMIT;
