export const SUMMARY_POLL_INTERVAL_MS = 15_000;
export const SUMMARY_SAFETY_POLL_INTERVAL_MS = 180_000;
export const SUMMARY_INVALIDATION_DEBOUNCE_MS = 250;
export const SUMMARY_STALE_AFTER_MS = 360_000;
